global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 1m
  receiver: "email-notifications"

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "patata.potato@sumup.com"
        from: "alertmanager@example.com"
        smarthost: "mailhog:1025"
        require_tls: false
        send_resolved: true
        html: '{{ template "email.default.html" . }}'
        headers:
          Subject: '{{ template "__subject" . }}'
          From: "Alertmanager <alertmanager@example.com>"
