CREATE TABLE IF NOT EXISTS payments (
    id SERIAL PRIMARY KEY,
    value DECIMAL(10,2) NOT NULL,
    app_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
